In [1]:
import numpy as np

# Elementwise Operations

<b>1. Basic Operations</b>

<b>with scalars</b>

In [2]:
a = np.array([1, 2, 3, 4]) # create an array

a + 1

array([2, 3, 4, 5])

In [3]:
a ** 2

array([ 1,  4,  9, 16])

<b>All arithmetic operation elementwise</b>

In [4]:
a = np.array([1, 2, 3, 4])
b = np.ones(4) + 1
a - b

array([-1.,  0.,  1.,  2.])

In [5]:
a * b

array([2., 4., 6., 8.])

In [6]:
# Matrix multiplication
c = np.diag([1, 2, 3, 4])
print(c * c)
print("***************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
***************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [7]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [8]:
a > b

array([False, False,  True, False])

In [9]:
# array-wise comparisions
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

np.array_equal(a, b)


False

In [10]:
np.array_equal(a, c)

True

<b>Logical Operstions</b>

In [11]:
a = np.array([1, 1, 0, 1], dtype=bool)
a = np.array([1, 0, 1, 1], dtype=bool)
np.logical_or(a, b)

array([ True,  True,  True,  True])

In [12]:
np.logical_and(a, b)

array([ True, False,  True,  True])

<b>Transcendental functions:</b>

In [13]:
a = np.arange(5)
print(a)
np.sin(a)

[0 1 2 3 4]


array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [14]:
np.log(a)

C:\Users\HP\AppData\Local\Temp\ipykernel_7312\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [15]:
np.exp(a) # evaluates e^x for each element in a given input

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

<b>Shape Mismatch</b>

In [16]:
a = np.arange(4)
a + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

## Basic Reductions

<b>computing sums</b>

In [ ]:
x = np.array([1, 2, 3, 4])
np.sum(x)

In [ ]:
# sum by rows and by columns
x = np.array([[1, 1], [2, 2]])
x

In [ ]:
x.sum(axis=0) # columns first dimension

In [ ]:
x.sum(axis=1) # row (second dimension)

<b>Other reductions</b>

In [ ]:
x = np.array([1, 3, 2])
x.min()

In [ ]:
x.max()

In [ ]:
x.argmin() # index of minimum element

In [ ]:
x.argmax() # index of maximum element

<b>Logical Operations</b>

In [ ]:
np.all([True, True, False])

In [ ]:
np.any([True, False, False])

In [ ]:
#Note: can be used for array comparisions
a = np.zeros((50, 50))
np.any(a != 0)

In [ ]:
np.all(a == a)

In [ ]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
b = np.array([6, 4, 4, 5])
((a <= b) & (b <= c)).all()

<b>Statistics</b>

In [ ]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

In [ ]:
np.median(y, axis=-1) # last axis

In [ ]:
x.std() # full population standard dev.

<b>Example:</b>

Data in population.txt describes the populations of hares and lynxes (and carrots) in norther Canada during 20 years.

In [ ]:
import random

# Number of years

years = 20

# Generating sample data
data = []
for year in range(1, years + 1):
    hares = random.randint(250, 350) # Random population fo rhares
    lynxes = random.randint(30, 60) # Random population for lynxes
    carrots = random.randint(450, 550) # Random population for carrots
    data.append([year, hares, lynxes, carrots])

# Writing the data to population.txt
with open('populations.txt', 'w') as file:
    # Writing the header
    #file.write("Year | Hares | Lynxes | Carrots\n")

    #Writing the data
    for entry in data:
        file.write(f"{entry[0]:>4} , {entry[1]:>5} , {entry[2]:>6} , {entry[3]:>7}\n")

print("Data has been written to population.txt")

In [ ]:
# load data into numpy array object
data = np.loadtxt('populations.txt', delimiter=',')
print(data)

### 

In [ ]:
year, hares, lynxes, carrots = data.T # columns to variables
print(year)

In [ ]:
# The mean population over time
populations = data[:, 1:]
populations

In [ ]:
# sample standard deviations
populations.std(axis=0)

In [ ]:
# which species has the highest population each year ?
np.argmax(populations, axis=1)

## Broadcasting

Basic operations on numpy arrays (addition, etc) are element wise
This works on array of the same size. Nevertheless, it's also possible to do operation on arrays of different sizes if NumPy can transform these arrays so that they all have same size: this conversion is called broadcasting.

The image below gives an example of broadcasting:

<img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png" alt="NumPy broadcasting" width="500" height="600">

In [ ]:
a = np.tile(np.arange(0, 40, 10), (3, 1))
print(a)

print("************")
a = a.T
print(a)

In [ ]:
b = np.array([0, 1, 2])
b

In [ ]:
a + b

In [ ]:
a = np.arange(0, 40, 10)
a.shape

In [ ]:
a = a[:, np.newaxis] # adds a new axis -> 2D
a.shape

In [ ]:
a

In [ ]:
a + b

## Array Shape manipulation

<b>Flattening</b>

In [17]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ravel() # Return a contiguous flattened array. A 1-D array, containing the array

array([1, 2, 3, 4, 5, 6])

In [18]:
a.T # Transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [19]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

<b>Reshaping</b>

The inverse operation to flattening:

In [22]:
print(a)
print(a.shape)
print(a)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3]
 [4 5 6]]
